name: Trigger auto deployment for mss-saas-contapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ AICopilote ]
    paths:
    - '**'
    - '.github/workflows/mss-saas-contapp-AutoDeployTrigger-f76e4cfc-5b67-4c10-8bcb-22d5791c545b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MSSSAASCONTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MSSSAASCONTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MSSSAASCONTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 651d5c590cea446b882efa81a636b67c.azurecr.io
          registryUsername: ${{ secrets.MSSSAASCONTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MSSSAASCONTAPP_REGISTRY_PASSWORD }}
          containerAppName: mss-saas-contapp
          resourceGroup: RG-EU-MSS_SaaS_Agent
          imageToBuild: 651d5c590cea446b882efa81a636b67c.azurecr.io/mss-saas-contapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


